# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EnterURL.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(590, 247)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(95, 101, 111);\n"
"    border-radius: 3px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 551, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 40))
        self.label_2.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color:#fff;\n"
"    margin-left: 5px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border: 0.5px solid #000;\n"
"    selection-color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(0, 220, 106);\n"
"    color:#000;\n"
"    background-color: #e1e1e1;\n"
"    border-radius: 2px;\n"
"    margin-left: 5px;\n"
"    margin-right: 5px;\n"
"}")
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.status = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.status.setFont(font)
        self.status.setText("")
        self.status.setObjectName("status")
        self.horizontalLayout_2.addWidget(self.status)
        self.cancel = QtWidgets.QPushButton(self.layoutWidget)
        self.cancel.setMaximumSize(QtCore.QSize(100, 25))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        self.ok = QtWidgets.QPushButton(self.layoutWidget)
        self.ok.setMaximumSize(QtCore.QSize(100, 25))
        self.ok.setStyleSheet("")
        self.ok.setObjectName("ok")
        self.horizontalLayout_2.addWidget(self.ok)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 400, 561, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.download = QtWidgets.QPushButton(self.layoutWidget1)
        self.download.setMinimumSize(QtCore.QSize(100, 30))
        self.download.setMaximumSize(QtCore.QSize(100, 16777215))
        self.download.setStyleSheet("QPushButton{\n"
"    background-color: rgb(215, 134, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(106, 255, 123);\n"
"    border-radius: 3px;\n"
"}")
        self.download.setObjectName("download")
        self.horizontalLayout.addWidget(self.download)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(20, 300, 271, 81))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.video_title = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.video_title.setFont(font)
        self.video_title.setText("")
        self.video_title.setObjectName("video_title")
        self.verticalLayout_2.addWidget(self.video_title)
        self.video_duration = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.video_duration.setFont(font)
        self.video_duration.setText("")
        self.video_duration.setObjectName("video_duration")
        self.verticalLayout_2.addWidget(self.video_duration)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Enter URL"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p>Enter URL</p></body></html>"))
        self.cancel.setText(_translate("Dialog", "Cancel"))
        self.cancel.setShortcut(_translate("Dialog", "Ctrl+Z"))
        self.ok.setText(_translate("Dialog", "OK"))
        self.ok.setShortcut(_translate("Dialog", "Ctrl+O"))
        self.download.setText(_translate("Dialog", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
